-- Populate Knowledge Base with Comprehensive Q&A
-- This file contains initial Q&A pairs for the live chat system

-- Account Management
INSERT INTO knowledge_base (question, question_normalized, answer, category, keywords, created_by) VALUES
('How do I create an account?', 'how do i create an account', 'To create an account, click the "Sign Up" button on the top right corner of the homepage. Fill in your name, email, phone number, and password. You will receive a verification code via email or SMS to complete registration.', 'account', '["register", "signup", "new account"]', 1),
('How do I log in to my account?', 'how do i log in to my account', 'Click the "Login" button on the top right corner. Enter your email and password, then click "Sign In". If you forgot your password, click "Forgot Password" to reset it.', 'account', '["login", "signin", "access"]', 1),
('How do I reset my password?', 'how do i reset my password', 'Click "Forgot Password" on the login page. Enter your email address and you will receive a reset link via email. Follow the instructions to create a new password.', 'account', '["password", "reset", "forgot"]', 1),
('How do I update my profile information?', 'how do i update my profile information', 'Go to your account dashboard and click on "Profile". You can update your name, email, phone, address, and region. Click "Save Changes" to update your information.', 'account', '["profile", "update", "edit"]', 1),
('How do I change my profile picture?', 'how do i change my profile picture', 'In your profile settings, click on the profile picture area to upload a new image. Supported formats include JPG, PNG, and GIF. The image will be automatically resized.', 'account', '["avatar", "picture", "photo"]', 1),

-- Product Browsing and Search
('How do I search for products?', 'how do i search for products', 'Use the search bar at the top of the page. You can search by product name, category, or technical specifications. The search supports fuzzy matching and will show relevant results even with partial matches.', 'products', '["search", "find", "look for"]', 1),
('How do I filter products?', 'how do i filter products', 'On the Shop page, use the filter panel on the left to filter by category, price range, minimum rating, and discount percentage. You can apply multiple filters at once.', 'products', '["filter", "narrow", "refine"]', 1),
('How do I compare products?', 'how do i compare products', 'Click the "Compare" button on any product card to add it to your comparison bar. You can compare up to 4 products side-by-side, viewing their specifications, prices, and features in a unified table.', 'products', '["compare", "difference", "versus"]', 1),
('What do the stock labels mean?', 'what do the stock labels mean', '"Only X left!" indicates limited remaining stock, while "Selling fast" shows items with high recent demand. These labels help you make timely purchasing decisions.', 'products', '["stock", "availability", "labels"]', 1),
('How do I view product specifications?', 'how do i view product specifications', 'Click on any product to view its detailed page. The specifications section shows technical details like voltage, current, dimensions, and other relevant parameters.', 'products', '["specs", "specifications", "details"]', 1),

-- Shopping Cart and Checkout
('How do I add items to my cart?', 'how do i add items to my cart', 'Click the "Add to Cart" button on any product card. The item will be added to your shopping cart. You can view your cart by clicking the cart icon in the top right corner.', 'cart', '["add", "cart", "shopping"]', 1),
('How do I remove items from my cart?', 'how do i remove items from my cart', 'Go to your cart page and click the "Remove" button next to the item you want to delete. You can also adjust quantities using the +/- buttons.', 'cart', '["remove", "delete", "cart"]', 1),
('How do I apply a promo code?', 'how do i apply a promo code', 'During checkout, you will find a promo code field in the order summary section. Enter your flash sale code and click "Apply". The discount will be instantly reflected in your total.', 'cart', '["promo", "discount", "coupon"]', 1),
('What payment methods do you accept?', 'what payment methods do you accept', 'We accept payments via Paystack (card, mobile money, bank transfer) and cash on delivery for pickup orders. All transactions are secure and encrypted.', 'cart', '["payment", "pay", "methods"]', 1),
('How do I complete my order?', 'how do i complete my order', 'After adding items to your cart, proceed to checkout. Fill in your shipping address, select a delivery method, choose payment method, and review your order. Click "Place Order" to complete the purchase.', 'cart', '["checkout", "complete", "finish"]', 1),

-- Order Management
('How do I make an order?', 'how do i make an order', 'Add products to your cart, then proceed to checkout. Fill in your shipping details, select delivery method (pickup or door-to-door), choose payment method, and click "Place Order" to complete your purchase.', 'orders', '["order", "buy", "purchase"]', 1),
('How do I track my order?', 'how do i track my order', 'Go to the Orders page in your dashboard to see a live timeline of your order status. The timeline shows each stage from processing to delivery, with real-time updates as your order progresses.', 'orders', '["track", "status", "timeline"]', 1),
('How do I cancel my order?', 'how do i cancel my order', 'Orders can be cancelled within 1 hour of placement by contacting our support team immediately. Orders already in processing cannot be cancelled. Go to your Orders page and use the "Cancel Order" button if available.', 'orders', '["cancel", "stop", "abort"]', 1),
('What order statuses are there?', 'what order statuses are there', 'Order statuses include: Pending (awaiting processing), Processing (being prepared), Shipped (on the way), Delivered (completed), and Cancelled (order cancelled). You can track these in your Orders dashboard.', 'orders', '["status", "states", "stages"]', 1),
('How do I view my order history?', 'how do i view my order history', 'Go to the Orders page in your dashboard. All your past and current orders are listed there with their status, total amount, and date. Click on any order to view detailed information.', 'orders', '["history", "past", "previous"]', 1),

-- Returns and Refunds
('What is your return policy?', 'what is your return policy', 'We accept returns for DOA (dead-on-arrival) or damaged components and unopened STEM kits within 14 days. Opened component packs and ESD-damaged items are not eligible for return.', 'returns', '["return", "policy", "refund"]', 1),
('How do I request a return?', 'how do i request a return', 'Go to your Orders page, find the order you want to return, and click "Request Return". Select the items you want to return, provide a reason, and submit your request. Our team will review and approve it.', 'returns', '["return", "request", "send back"]', 1),
('How do refunds work?', 'how do refunds work', 'For multi-item returns, we consolidate refunds into a single transaction to keep your statement clean. Refunds are processed back to your original payment method (Paystack) or via cash within 5-7 business days.', 'returns', '["refund", "money back", "credit"]', 1),
('Can I return multiple items at once?', 'can i return multiple items at once', 'Yes! You can select and request returns for multiple items from the same order at once through your dashboard''s Return Manager. This makes the process more efficient.', 'returns', '["multiple", "several", "batch"]', 1),
('What items cannot be returned?', 'what items cannot be returned', 'Opened component packs, ESD-damaged items, and items beyond the 14-day return window cannot be returned. Special order items may also have different return policies.', 'returns', '["cannot", "not eligible", "excluded"]', 1),

-- Wishlist and Favorites
('How do I add items to my wishlist?', 'how do i add items to my wishlist', 'Click the heart icon on any product card to add it to your wishlist. You can access your wishlist from your dashboard or by clicking the wishlist icon in the navigation.', 'wishlist', '["wishlist", "favorites", "save"]', 1),
('How do I remove items from my wishlist?', 'how do i remove items from my wishlist', 'Go to your Favorites page and click the "Remove" button next to any item you want to delete from your wishlist.', 'wishlist', '["remove", "delete", "unsave"]', 1),
('How do I move items from wishlist to cart?', 'how do i move items from wishlist to cart', 'On your Favorites page, click the "Add to Cart" button on any item. It will be added to your shopping cart and remain in your wishlist for future reference.', 'wishlist', '["move", "transfer", "cart"]', 1),
('What is the difference between wishlist and favorites?', 'what is the difference between wishlist and favorites', 'They are the same feature - your wishlist is also called your Favorites. It''s a place to save products you''re interested in for later purchase.', 'wishlist', '["difference", "same", "versus"]', 1),

-- Shipping and Delivery
('What delivery methods do you offer?', 'what delivery methods do you offer', 'We offer two delivery methods: Pickup (collect from our store) and Door-to-Door (delivery to your address). Pickup is free, while door-to-door has a shipping fee based on your region.', 'shipping', '["delivery", "shipping", "methods"]', 1),
('How much does shipping cost?', 'how much does shipping cost', 'Shipping costs depend on your region. Local delivery (Greater Accra) costs 15 GHS, while regional delivery costs 35 GHS. Orders over 1500 GHS get 50% off shipping fees.', 'shipping', '["cost", "fee", "price"]', 1),
('How long does delivery take?', 'how long does delivery take', 'Local delivery (Greater Accra) typically takes 1-2 business days. Regional delivery takes 2-5 business days depending on your location. You can track your order status in real-time.', 'shipping', '["time", "duration", "how long"]', 1),
('Can I change my delivery address?', 'can i change my delivery address', 'You can change your delivery address only if your order is still in "Pending" status. Once processing begins, the address cannot be changed. Contact support immediately if you need to make changes.', 'shipping', '["address", "change", "location"]', 1),
('What are pickup locations?', 'what are pickup locations', 'We have multiple pickup locations across Greater Accra. During checkout with pickup selected, you can choose the most convenient location for you to collect your order.', 'shipping', '["pickup", "location", "collect"]', 1),

-- Discounts and Promotions
('What are flash sales?', 'what are flash sales', 'Flash sales are limited-time promotions with significant discounts on selected products. They have expiration dates, so use the promo codes before they expire to get the discounted price.', 'discounts', '["flash sale", "promotion", "deal"]', 1),
('How do I get discount codes?', 'how do i get discount codes', 'Discount codes are sent via email, SMS, or announced on our website. Subscribe to our newsletter and follow our social media to stay updated on the latest promotions.', 'discounts', '["codes", "coupons", "promotions"]', 1),
('Do you offer bulk discounts?', 'do you offer bulk discounts', 'Yes! We offer competitive bulk discounts for institutions, universities, and engineering firms. Email us with your parts list and quantities for a custom quote.', 'discounts', '["bulk", "wholesale", "quantity"]', 1),
('What is the loyalty points system?', 'what is the loyalty points system', 'Earn loyalty points with every purchase. Points can be redeemed for discounts on future orders. Higher spending levels (Elite, VIP) earn more points per purchase.', 'discounts', '["loyalty", "points", "rewards"]', 1),
('How do I check my loyalty level?', 'how do i check my loyalty level', 'Your loyalty level is displayed in your account dashboard. Levels include Starter, Elite (500+ GHS spent), and VIP (2000+ GHS spent). Higher levels get better rewards and discounts.', 'discounts', '["level", "tier", "status"]', 1),

-- Account Settings
('How do I change my theme?', 'how do i change my theme', 'Go to your account settings and select your preferred theme (Light or Dark mode). The setting applies across all pages of the website.', 'settings', '["theme", "dark mode", "light mode"]', 1),
('How do I manage my notifications?', 'how do i manage my notifications', 'In your account settings, you can enable or disable email notifications, push notifications, and SMS tracking for orders and promotions.', 'settings', '["notifications", "alerts", "preferences"]', 1),
('How do I delete my account?', 'how do i delete my account', 'To delete your account, please contact our support team. We will process your request after verifying your identity. Note that this action is irreversible and all your data will be permanently deleted.', 'settings', '["delete", "remove", "close"]', 1),
('How do I verify my email?', 'how do i verify my email', 'After registration, you will receive a verification email. Click the link in the email to verify your account. If you didn''t receive it, check your spam folder or request a new verification code.', 'settings', '["verify", "email", "confirm"]', 1),
('How do I verify my phone number?', 'how do i verify my phone number', 'During registration, you can choose SMS verification. You will receive a code via SMS to verify your phone number. Enter the code to complete verification.', 'settings', '["verify", "phone", "sms"]', 1),

-- Product Information
('Are your components genuine?', 'are your components genuine', 'Yes. All components are sourced from verified suppliers and authorized distributors. We guarantee authenticity and provide datasheets on request for ICs, transistors, and modules.', 'products', '["genuine", "authentic", "original"]', 1),
('Do you provide datasheets?', 'do you provide datasheets', 'Yes. For most ICs, sensors, and modules we can provide the manufacturer datasheet on request. Contact us with the part number and we''ll send it within 24 hours.', 'products', '["datasheet", "documentation", "specs"]', 1),
('What is DOA warranty?', 'what is doa warranty', 'DOA (Dead-On-Arrival) warranty covers components that are defective upon delivery. We replace DOA items free of charge within 14 days of delivery.', 'products', '["doa", "warranty", "defective"]', 1),
('How do I identify the right component?', 'how do i identify the right component', 'Use our search and filter features to find components by specifications. You can also compare multiple products side-by-side to choose the right one for your project.', 'products', '["identify", "choose", "select"]', 1),
('Do you sell STEM kits?', 'do you sell stem kits', 'Yes! We offer a variety of STEM kits for education and hobby projects. These include complete project kits with all necessary components and instructions.', 'products', '["stem", "kits", "education"]', 1),

-- Support and Help
('How do I contact support?', 'how do i contact support', 'You can reach us via Live Chat (available on the Support page), WhatsApp, phone, or email. Our support team is available 9am-6pm on weekdays.', 'support', '["contact", "support", "help"]', 1),
('What is the live chat response time?', 'what is the live chat response time', 'Our average response time is under 1 minute for all active sessions. If your question isn''t in our knowledge base, it will be redirected to a human agent.', 'support', '["response time", "wait", "speed"]', 1),
('How do I report a problem with my order?', 'how do i report a problem with my order', 'Go to your Orders page, find the problematic order, and click "Report Issue". Describe the problem and our team will investigate and resolve it promptly.', 'support', '["report", "problem", "issue"]', 1),
('Can I get technical help with products?', 'can i get technical help with products', 'Yes! Our support team includes technical experts who can help with product selection, usage questions, and troubleshooting. Contact us via Live Chat or email for technical assistance.', 'support', '["technical", "help", "assistance"]', 1),
('How do I give feedback?', 'how do i give feedback', 'We value your feedback! You can rate answers in the live chat, leave product reviews, or email us directly with suggestions and comments.', 'support', '["feedback", "review", "suggestion"]', 1);
